%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,8,1},{11,46,20}}

-ifndef(cortet_sample_func).
-define(cortet_sample_func, true).

-define(cortet_sample_func_gpb_version, "3.21.0").

-ifndef('CORTET.SAMPLE.FUNC.CALL_PB_H').
-define('CORTET.SAMPLE.FUNC.CALL_PB_H', true).
-record('cortet.sample.func.Call',
        {
        }).
-endif.

-ifndef('CORTET.SAMPLE.TYPE.TYPE_PB_H').
-define('CORTET.SAMPLE.TYPE.TYPE_PB_H', true).
-record('cortet.sample.type.Type',
        {
        }).
-endif.

-endif.
