%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,8,1},{11,46,20}}

-ifndef(saya_ingw_wafa_func).
-define(saya_ingw_wafa_func, true).

-define(saya_ingw_wafa_func_gpb_version, "3.21.0").

-ifndef('SAYA.INGW.WAFA.FUNC.PING_PB_H').
-define('SAYA.INGW.WAFA.FUNC.PING_PB_H', true).
-record('saya.ingw.wafa.func.Ping',
        {'MicroTimeStamp'               % = 1, fixed64
        }).
-endif.

-ifndef('SAYA.INGW.WAFA.TYPE.CONVERSATION_PB_H').
-define('SAYA.INGW.WAFA.TYPE.CONVERSATION_PB_H', true).
-record('saya.ingw.wafa.type.Conversation',
        {'CID'                          % = 1, fixed64
        }).
-endif.

-ifndef('SAYA.INGW.COMN.TYPE.PONG_PB_H').
-define('SAYA.INGW.COMN.TYPE.PONG_PB_H', true).
-record('saya.ingw.comn.type.Pong',
        {'MicroTimeStamp'               % = 1, fixed64
        }).
-endif.

-ifndef('SAYA.INGW.COMN.TYPE.DONE_PB_H').
-define('SAYA.INGW.COMN.TYPE.DONE_PB_H', true).
-record('saya.ingw.comn.type.Done',
        {
        }).
-endif.

-ifndef('SAYA.INGW.WAFA.TYPE.BOARD_PB_H').
-define('SAYA.INGW.WAFA.TYPE.BOARD_PB_H', true).
-record('saya.ingw.wafa.type.Board',
        {'BID'                          % = 1, fixed64
        }).
-endif.

-ifndef('SAYA.INGW.WAFA.TYPE.TIMELINE_PB_H').
-define('SAYA.INGW.WAFA.TYPE.TIMELINE_PB_H', true).
-record('saya.ingw.wafa.type.Timeline',
        {a                              % oneof
        }).
-endif.

-ifndef('SAYA.INGW.WAFA.TYPE.MESSAGE_PB_H').
-define('SAYA.INGW.WAFA.TYPE.MESSAGE_PB_H', true).
-record('saya.ingw.wafa.type.Message',
        {timestamp,                     % = 1, fixed64
         senderIID,                     % = 2, fixed64
         seq,                           % = 3, int64
         timeline,                      % = 4, {msg,'saya.ingw.wafa.type.Timeline'}
         body                           % = 5, string
        }).
-endif.

-ifndef('SAYA.INGW.WAFA.FUNC.DOSECURITYCHECK_PB_H').
-define('SAYA.INGW.WAFA.FUNC.DOSECURITYCHECK_PB_H', true).
-record('saya.ingw.wafa.func.DoSecurityCheck',
        {message = []                   % = 1, [{msg,'saya.ingw.wafa.type.Message'}]
        }).
-endif.

-ifndef('SAYA.INGW.COMN.TYPE.FAILURE_PB_H').
-define('SAYA.INGW.COMN.TYPE.FAILURE_PB_H', true).
-record('saya.ingw.comn.type.Failure',
        {code,                          % = 1, {enum,'saya.ingw.comn.type.FailureCode'}
         description                    % = 2, string (optional)
        }).
-endif.

-endif.
