%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,8,1},{11,46,20}}

-ifndef(saya_ingw_comn_type).
-define(saya_ingw_comn_type, true).

-define(saya_ingw_comn_type_gpb_version, "3.21.0").

-ifndef('SAYA.INGW.COMN.TYPE.PONG_PB_H').
-define('SAYA.INGW.COMN.TYPE.PONG_PB_H', true).
-record('saya.ingw.comn.type.Pong',
        {'MicroTimeStamp'               % = 1, fixed64
        }).
-endif.

-ifndef('SAYA.INGW.COMN.TYPE.DONE_PB_H').
-define('SAYA.INGW.COMN.TYPE.DONE_PB_H', true).
-record('saya.ingw.comn.type.Done',
        {
        }).
-endif.

-ifndef('SAYA.INGW.COMN.TYPE.FAILURE_PB_H').
-define('SAYA.INGW.COMN.TYPE.FAILURE_PB_H', true).
-record('saya.ingw.comn.type.Failure',
        {code,                          % = 1, {enum,'saya.ingw.comn.type.FailureCode'}
         description                    % = 2, string (optional)
        }).
-endif.

-endif.
