%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,8,1},{11,46,20}}
-module(saya_ingw_comn_type).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2]).
-export([merge_msgs/2]).
-export([verify_msg/1]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_saya.ingw.comn.type.FailureCode'/1, 'enum_value_by_symbol_saya.ingw.comn.type.FailureCode'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("saya_ingw_comn_type.hrl").
-include("gpb.hrl").



encode_msg(Msg) -> encode_msg(Msg, []).


encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg);
      false -> ok
    end,
    case Msg of
      #'saya.ingw.comn.type.Pong'{} ->
	  'e_msg_saya.ingw.comn.type.Pong'(Msg);
      #'saya.ingw.comn.type.Done'{} ->
	  'e_msg_saya.ingw.comn.type.Done'(Msg);
      #'saya.ingw.comn.type.Failure'{} ->
	  'e_msg_saya.ingw.comn.type.Failure'(Msg)
    end.


'e_msg_saya.ingw.comn.type.Pong'(Msg) ->
    'e_msg_saya.ingw.comn.type.Pong'(Msg, <<>>).


'e_msg_saya.ingw.comn.type.Pong'(#'saya.ingw.comn.type.Pong'{'MicroTimeStamp'
								 = F1},
				 Bin) ->
    e_type_fixed64(F1, <<Bin/binary, 9>>).

'e_msg_saya.ingw.comn.type.Done'(_Msg) -> <<>>.

'e_msg_saya.ingw.comn.type.Failure'(Msg) ->
    'e_msg_saya.ingw.comn.type.Failure'(Msg, <<>>).


'e_msg_saya.ingw.comn.type.Failure'(#'saya.ingw.comn.type.Failure'{code
								       = F1,
								   description =
								       F2},
				    Bin) ->
    B1 = 'e_enum_saya.ingw.comn.type.FailureCode'(F1,
						  <<Bin/binary, 8>>),
    if F2 == undefined -> B1;
       true -> e_type_string(F2, <<B1/binary, 18>>)
    end.



'e_enum_saya.ingw.comn.type.FailureCode'('INTERNAL_SERVER_ERROR',
					 Bin) ->
    <<Bin/binary, 1>>;
'e_enum_saya.ingw.comn.type.FailureCode'('INVALID_REQUEST',
					 Bin) ->
    <<Bin/binary, 2>>.

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_type_fixed64(Value, Bin) ->
    <<Bin/binary, Value:64/little>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    case MsgName of
      'saya.ingw.comn.type.Pong' ->
	  'd_msg_saya.ingw.comn.type.Pong'(Bin);
      'saya.ingw.comn.type.Done' ->
	  'd_msg_saya.ingw.comn.type.Done'(Bin);
      'saya.ingw.comn.type.Failure' ->
	  'd_msg_saya.ingw.comn.type.Failure'(Bin)
    end.



'd_msg_saya.ingw.comn.type.Pong'(Bin) ->
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Bin, 0, 0,
						  id(undefined)).

'dfp_read_field_def_saya.ingw.comn.type.Pong'(<<9,
						Rest/binary>>,
					      Z1, Z2, F1) ->
    'd_field_saya.ingw.comn.type.Pong_MicroTimeStamp'(Rest,
						      Z1, Z2, F1);
'dfp_read_field_def_saya.ingw.comn.type.Pong'(<<>>, 0,
					      0, F1) ->
    #'saya.ingw.comn.type.Pong'{'MicroTimeStamp' = F1};
'dfp_read_field_def_saya.ingw.comn.type.Pong'(Other, Z1,
					      Z2, F1) ->
    'dg_read_field_def_saya.ingw.comn.type.Pong'(Other, Z1,
						 Z2, F1).

'dg_read_field_def_saya.ingw.comn.type.Pong'(<<1:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1)
    when N < 32 - 7 ->
    'dg_read_field_def_saya.ingw.comn.type.Pong'(Rest,
						 N + 7, X bsl N + Acc, F1);
'dg_read_field_def_saya.ingw.comn.type.Pong'(<<0:1, X:7,
					       Rest/binary>>,
					     N, Acc, F1) ->
    Key = X bsl N + Acc,
    case Key of
      9 ->
	  'd_field_saya.ingw.comn.type.Pong_MicroTimeStamp'(Rest,
							    0, 0, F1);
      _ ->
	  case Key band 7 of
	    0 ->
		'skip_varint_saya.ingw.comn.type.Pong'(Rest, 0, 0, F1);
	    1 -> 'skip_64_saya.ingw.comn.type.Pong'(Rest, 0, 0, F1);
	    2 ->
		'skip_length_delimited_saya.ingw.comn.type.Pong'(Rest,
								 0, 0, F1);
	    5 -> 'skip_32_saya.ingw.comn.type.Pong'(Rest, 0, 0, F1)
	  end
    end;
'dg_read_field_def_saya.ingw.comn.type.Pong'(<<>>, 0, 0,
					     F1) ->
    #'saya.ingw.comn.type.Pong'{'MicroTimeStamp' = F1}.

'd_field_saya.ingw.comn.type.Pong_MicroTimeStamp'(<<Value:64/little,
						    Rest/binary>>,
						  Z1, Z2, _) ->
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Rest, Z1,
						  Z2, Value).


'skip_varint_saya.ingw.comn.type.Pong'(<<1:1, _:7,
					 Rest/binary>>,
				       Z1, Z2, F1) ->
    'skip_varint_saya.ingw.comn.type.Pong'(Rest, Z1, Z2,
					   F1);
'skip_varint_saya.ingw.comn.type.Pong'(<<0:1, _:7,
					 Rest/binary>>,
				       Z1, Z2, F1) ->
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Rest, Z1,
						  Z2, F1).


'skip_length_delimited_saya.ingw.comn.type.Pong'(<<1:1,
						   X:7, Rest/binary>>,
						 N, Acc, F1)
    when N < 57 ->
    'skip_length_delimited_saya.ingw.comn.type.Pong'(Rest,
						     N + 7, X bsl N + Acc, F1);
'skip_length_delimited_saya.ingw.comn.type.Pong'(<<0:1,
						   X:7, Rest/binary>>,
						 N, Acc, F1) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Rest2, 0,
						  0, F1).


'skip_32_saya.ingw.comn.type.Pong'(<<_:32,
				     Rest/binary>>,
				   Z1, Z2, F1) ->
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Rest, Z1,
						  Z2, F1).


'skip_64_saya.ingw.comn.type.Pong'(<<_:64,
				     Rest/binary>>,
				   Z1, Z2, F1) ->
    'dfp_read_field_def_saya.ingw.comn.type.Pong'(Rest, Z1,
						  Z2, F1).


'd_msg_saya.ingw.comn.type.Done'(Bin) ->
    'dfp_read_field_def_saya.ingw.comn.type.Done'(Bin, 0,
						  0).

'dfp_read_field_def_saya.ingw.comn.type.Done'(<<>>, 0,
					      0) ->
    #'saya.ingw.comn.type.Done'{};
'dfp_read_field_def_saya.ingw.comn.type.Done'(Other, Z1,
					      Z2) ->
    'dg_read_field_def_saya.ingw.comn.type.Done'(Other, Z1,
						 Z2).

'dg_read_field_def_saya.ingw.comn.type.Done'(<<1:1, X:7,
					       Rest/binary>>,
					     N, Acc)
    when N < 32 - 7 ->
    'dg_read_field_def_saya.ingw.comn.type.Done'(Rest,
						 N + 7, X bsl N + Acc);
'dg_read_field_def_saya.ingw.comn.type.Done'(<<0:1, X:7,
					       Rest/binary>>,
					     N, Acc) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> 'skip_varint_saya.ingw.comn.type.Done'(Rest, 0, 0);
      1 -> 'skip_64_saya.ingw.comn.type.Done'(Rest, 0, 0);
      2 ->
	  'skip_length_delimited_saya.ingw.comn.type.Done'(Rest,
							   0, 0);
      5 -> 'skip_32_saya.ingw.comn.type.Done'(Rest, 0, 0)
    end;
'dg_read_field_def_saya.ingw.comn.type.Done'(<<>>, 0,
					     0) ->
    #'saya.ingw.comn.type.Done'{}.

'skip_varint_saya.ingw.comn.type.Done'(<<1:1, _:7,
					 Rest/binary>>,
				       Z1, Z2) ->
    'skip_varint_saya.ingw.comn.type.Done'(Rest, Z1, Z2);
'skip_varint_saya.ingw.comn.type.Done'(<<0:1, _:7,
					 Rest/binary>>,
				       Z1, Z2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Done'(Rest, Z1,
						  Z2).


'skip_length_delimited_saya.ingw.comn.type.Done'(<<1:1,
						   X:7, Rest/binary>>,
						 N, Acc)
    when N < 57 ->
    'skip_length_delimited_saya.ingw.comn.type.Done'(Rest,
						     N + 7, X bsl N + Acc);
'skip_length_delimited_saya.ingw.comn.type.Done'(<<0:1,
						   X:7, Rest/binary>>,
						 N, Acc) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_saya.ingw.comn.type.Done'(Rest2, 0,
						  0).


'skip_32_saya.ingw.comn.type.Done'(<<_:32,
				     Rest/binary>>,
				   Z1, Z2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Done'(Rest, Z1,
						  Z2).


'skip_64_saya.ingw.comn.type.Done'(<<_:64,
				     Rest/binary>>,
				   Z1, Z2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Done'(Rest, Z1,
						  Z2).


'd_msg_saya.ingw.comn.type.Failure'(Bin) ->
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Bin, 0,
						     0, id(undefined),
						     id(undefined)).

'dfp_read_field_def_saya.ingw.comn.type.Failure'(<<8,
						   Rest/binary>>,
						 Z1, Z2, F1, F2) ->
    'd_field_saya.ingw.comn.type.Failure_code'(Rest, Z1, Z2,
					       F1, F2);
'dfp_read_field_def_saya.ingw.comn.type.Failure'(<<18,
						   Rest/binary>>,
						 Z1, Z2, F1, F2) ->
    'd_field_saya.ingw.comn.type.Failure_description'(Rest,
						      Z1, Z2, F1, F2);
'dfp_read_field_def_saya.ingw.comn.type.Failure'(<<>>,
						 0, 0, F1, F2) ->
    #'saya.ingw.comn.type.Failure'{code = F1,
				   description = F2};
'dfp_read_field_def_saya.ingw.comn.type.Failure'(Other,
						 Z1, Z2, F1, F2) ->
    'dg_read_field_def_saya.ingw.comn.type.Failure'(Other,
						    Z1, Z2, F1, F2).

'dg_read_field_def_saya.ingw.comn.type.Failure'(<<1:1,
						  X:7, Rest/binary>>,
						N, Acc, F1, F2)
    when N < 32 - 7 ->
    'dg_read_field_def_saya.ingw.comn.type.Failure'(Rest,
						    N + 7, X bsl N + Acc, F1,
						    F2);
'dg_read_field_def_saya.ingw.comn.type.Failure'(<<0:1,
						  X:7, Rest/binary>>,
						N, Acc, F1, F2) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  'd_field_saya.ingw.comn.type.Failure_code'(Rest, 0, 0,
						     F1, F2);
      18 ->
	  'd_field_saya.ingw.comn.type.Failure_description'(Rest,
							    0, 0, F1, F2);
      _ ->
	  case Key band 7 of
	    0 ->
		'skip_varint_saya.ingw.comn.type.Failure'(Rest, 0, 0,
							  F1, F2);
	    1 ->
		'skip_64_saya.ingw.comn.type.Failure'(Rest, 0, 0, F1,
						      F2);
	    2 ->
		'skip_length_delimited_saya.ingw.comn.type.Failure'(Rest,
								    0, 0, F1,
								    F2);
	    5 ->
		'skip_32_saya.ingw.comn.type.Failure'(Rest, 0, 0, F1,
						      F2)
	  end
    end;
'dg_read_field_def_saya.ingw.comn.type.Failure'(<<>>, 0,
						0, F1, F2) ->
    #'saya.ingw.comn.type.Failure'{code = F1,
				   description = F2}.

'd_field_saya.ingw.comn.type.Failure_code'(<<1:1, X:7,
					     Rest/binary>>,
					   N, Acc, F1, F2)
    when N < 57 ->
    'd_field_saya.ingw.comn.type.Failure_code'(Rest, N + 7,
					       X bsl N + Acc, F1, F2);
'd_field_saya.ingw.comn.type.Failure_code'(<<0:1, X:7,
					     Rest/binary>>,
					   N, Acc, _, F2) ->
    <<Tmp:32/signed-native>> = <<(X bsl N +
				    Acc):32/unsigned-native>>,
    NewFValue =
	'd_enum_saya.ingw.comn.type.FailureCode'(Tmp),
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest,
						     0, 0, NewFValue, F2).


'd_field_saya.ingw.comn.type.Failure_description'(<<1:1,
						    X:7, Rest/binary>>,
						  N, Acc, F1, F2)
    when N < 57 ->
    'd_field_saya.ingw.comn.type.Failure_description'(Rest,
						      N + 7, X bsl N + Acc, F1,
						      F2);
'd_field_saya.ingw.comn.type.Failure_description'(<<0:1,
						    X:7, Rest/binary>>,
						  N, Acc, F1, _) ->
    Len = X bsl N + Acc,
    <<Utf8:Len/binary, Rest2/binary>> = Rest,
    NewFValue = unicode:characters_to_list(Utf8, unicode),
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest2,
						     0, 0, F1, NewFValue).


'skip_varint_saya.ingw.comn.type.Failure'(<<1:1, _:7,
					    Rest/binary>>,
					  Z1, Z2, F1, F2) ->
    'skip_varint_saya.ingw.comn.type.Failure'(Rest, Z1, Z2,
					      F1, F2);
'skip_varint_saya.ingw.comn.type.Failure'(<<0:1, _:7,
					    Rest/binary>>,
					  Z1, Z2, F1, F2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest,
						     Z1, Z2, F1, F2).


'skip_length_delimited_saya.ingw.comn.type.Failure'(<<1:1,
						      X:7, Rest/binary>>,
						    N, Acc, F1, F2)
    when N < 57 ->
    'skip_length_delimited_saya.ingw.comn.type.Failure'(Rest,
							N + 7, X bsl N + Acc,
							F1, F2);
'skip_length_delimited_saya.ingw.comn.type.Failure'(<<0:1,
						      X:7, Rest/binary>>,
						    N, Acc, F1, F2) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest2,
						     0, 0, F1, F2).


'skip_32_saya.ingw.comn.type.Failure'(<<_:32,
					Rest/binary>>,
				      Z1, Z2, F1, F2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest,
						     Z1, Z2, F1, F2).


'skip_64_saya.ingw.comn.type.Failure'(<<_:64,
					Rest/binary>>,
				      Z1, Z2, F1, F2) ->
    'dfp_read_field_def_saya.ingw.comn.type.Failure'(Rest,
						     Z1, Z2, F1, F2).




'd_enum_saya.ingw.comn.type.FailureCode'(1) ->
    'INTERNAL_SERVER_ERROR';
'd_enum_saya.ingw.comn.type.FailureCode'(2) ->
    'INVALID_REQUEST'.



merge_msgs(Prev, New)
    when element(1, Prev) =:= element(1, New) ->
    case Prev of
      #'saya.ingw.comn.type.Pong'{} ->
	  'merge_msg_saya.ingw.comn.type.Pong'(Prev, New);
      #'saya.ingw.comn.type.Done'{} ->
	  'merge_msg_saya.ingw.comn.type.Done'(Prev, New);
      #'saya.ingw.comn.type.Failure'{} ->
	  'merge_msg_saya.ingw.comn.type.Failure'(Prev, New)
    end.

'merge_msg_saya.ingw.comn.type.Pong'(#'saya.ingw.comn.type.Pong'{'MicroTimeStamp'
								     =
								     PFMicroTimeStamp},
				     #'saya.ingw.comn.type.Pong'{'MicroTimeStamp'
								     =
								     NFMicroTimeStamp}) ->
    #'saya.ingw.comn.type.Pong'{'MicroTimeStamp' =
				    if NFMicroTimeStamp =:= undefined ->
					   PFMicroTimeStamp;
				       true -> NFMicroTimeStamp
				    end}.

'merge_msg_saya.ingw.comn.type.Done'(_Prev, New) -> New.

'merge_msg_saya.ingw.comn.type.Failure'(#'saya.ingw.comn.type.Failure'{code
									   =
									   PFcode,
								       description
									   =
									   PFdescription},
					#'saya.ingw.comn.type.Failure'{code =
									   NFcode,
								       description
									   =
									   NFdescription}) ->
    #'saya.ingw.comn.type.Failure'{code =
				       if NFcode =:= undefined -> PFcode;
					  true -> NFcode
				       end,
				   description =
				       if NFdescription =:= undefined ->
					      PFdescription;
					  true -> NFdescription
				       end}.



verify_msg(Msg) ->
    case Msg of
      #'saya.ingw.comn.type.Pong'{} ->
	  'v_msg_saya.ingw.comn.type.Pong'(Msg,
					   ['saya.ingw.comn.type.Pong']);
      #'saya.ingw.comn.type.Done'{} ->
	  'v_msg_saya.ingw.comn.type.Done'(Msg,
					   ['saya.ingw.comn.type.Done']);
      #'saya.ingw.comn.type.Failure'{} ->
	  'v_msg_saya.ingw.comn.type.Failure'(Msg,
					      ['saya.ingw.comn.type.Failure']);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


'v_msg_saya.ingw.comn.type.Pong'(#'saya.ingw.comn.type.Pong'{'MicroTimeStamp'
								 = F1},
				 Path) ->
    v_type_fixed64(F1, ['MicroTimeStamp' | Path]), ok.

'v_msg_saya.ingw.comn.type.Done'(#'saya.ingw.comn.type.Done'{},
				 _Path) ->
    ok.

'v_msg_saya.ingw.comn.type.Failure'(#'saya.ingw.comn.type.Failure'{code
								       = F1,
								   description =
								       F2},
				    Path) ->
    'v_enum_saya.ingw.comn.type.FailureCode'(F1,
					     [code | Path]),
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [description | Path])
    end,
    ok.

'v_enum_saya.ingw.comn.type.FailureCode'('INTERNAL_SERVER_ERROR',
					 _Path) ->
    ok;
'v_enum_saya.ingw.comn.type.FailureCode'('INVALID_REQUEST',
					 _Path) ->
    ok;
'v_enum_saya.ingw.comn.type.FailureCode'(X, Path) ->
    mk_type_error({invalid_enum,
		   'saya.ingw.comn.type.FailureCode'},
		  X, Path).

v_type_fixed64(N, _Path)
    when 0 =< N, N =< 18446744073709551615 ->
    ok;
v_type_fixed64(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, fixed64, unsigned,
		   64},
		  N, Path);
v_type_fixed64(X, Path) ->
    mk_type_error({bad_integer, fixed64, unsigned, 64}, X,
		  Path).

v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



-compile({nowarn_unused_function,id/1}).
-compile({inline,id/1}).
id(X) -> X.

-compile({nowarn_unused_function,cons/2}).
-compile({inline,cons/2}).
cons(Elem, Acc) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/1}).
-compile({inline,lists_reverse/1}).
'lists_reverse'(L) -> lists:reverse(L).

-compile({nowarn_unused_function,'erlang_++'/2}).
-compile({inline,'erlang_++'/2}).
'erlang_++'(A, B) -> A ++ B.



get_msg_defs() ->
    [{{enum, 'saya.ingw.comn.type.FailureCode'},
      [{'INTERNAL_SERVER_ERROR', 1}, {'INVALID_REQUEST', 2}]},
     {{msg, 'saya.ingw.comn.type.Pong'},
      [#field{name = 'MicroTimeStamp', fnum = 1, rnum = 2,
	      type = fixed64, occurrence = required, opts = []}]},
     {{msg, 'saya.ingw.comn.type.Done'}, []},
     {{msg, 'saya.ingw.comn.type.Failure'},
      [#field{name = code, fnum = 1, rnum = 2,
	      type = {enum, 'saya.ingw.comn.type.FailureCode'},
	      occurrence = required, opts = []},
       #field{name = description, fnum = 2, rnum = 3,
	      type = string, occurrence = optional, opts = []}]}].


get_msg_names() ->
    ['saya.ingw.comn.type.Pong', 'saya.ingw.comn.type.Done',
     'saya.ingw.comn.type.Failure'].


get_enum_names() -> ['saya.ingw.comn.type.FailureCode'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
      Es when is_list(Es) -> Es;
      error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def('saya.ingw.comn.type.Pong') ->
    [#field{name = 'MicroTimeStamp', fnum = 1, rnum = 2,
	    type = fixed64, occurrence = required, opts = []}];
find_msg_def('saya.ingw.comn.type.Done') -> [];
find_msg_def('saya.ingw.comn.type.Failure') ->
    [#field{name = code, fnum = 1, rnum = 2,
	    type = {enum, 'saya.ingw.comn.type.FailureCode'},
	    occurrence = required, opts = []},
     #field{name = description, fnum = 2, rnum = 3,
	    type = string, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def('saya.ingw.comn.type.FailureCode') ->
    [{'INTERNAL_SERVER_ERROR', 1}, {'INVALID_REQUEST', 2}];
find_enum_def(_) -> error.


enum_symbol_by_value('saya.ingw.comn.type.FailureCode',
		     Value) ->
    'enum_symbol_by_value_saya.ingw.comn.type.FailureCode'(Value).


enum_value_by_symbol('saya.ingw.comn.type.FailureCode',
		     Sym) ->
    'enum_value_by_symbol_saya.ingw.comn.type.FailureCode'(Sym).


'enum_symbol_by_value_saya.ingw.comn.type.FailureCode'(1) ->
    'INTERNAL_SERVER_ERROR';
'enum_symbol_by_value_saya.ingw.comn.type.FailureCode'(2) ->
    'INVALID_REQUEST'.


'enum_value_by_symbol_saya.ingw.comn.type.FailureCode'('INTERNAL_SERVER_ERROR') ->
    1;
'enum_value_by_symbol_saya.ingw.comn.type.FailureCode'('INVALID_REQUEST') ->
    2.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> 'saya.ingw.comn.type'.



gpb_version_as_string() ->
    "3.21.0".

gpb_version_as_list() ->
    [3,21,0].
